spring.application.name=backend
server.address=${HOST:127.0.0.1}
server.port=${PORT:4000}
spring.datasource.url=${DB_URL:jdbc:mariadb://127.0.0.1:3306/visualWork}
spring.datasource.username=${DB_USER:dbuser}
spring.datasource.password=${DB_PASSWORD:dudgns}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.sql.init.mode=never
server.error.include-message=never
springdoc.paths-to-match=/api/**,/health
